WITH  TBL AS(
    SELECT LAG(A_NUM) OVER (ORDER BY A_NUM) AS PRE_A_NUM,
           LAG(B_NUM) OVER (ORDER BY B_NUM) AS PRE_B_NUM,
           LAG(C_NUM) OVER (ORDER BY C_NUM) AS PRE_C_NUM,
           X.*
    FROM (
        SELECT ,DENSE_RANK() OVER(ORDER BY TBL.A ASC) AS A_NUM
               ,DENSE_RANK() OVER(ORDER BY TBL.A, TBL.B ASC) AS B_NUM
               ,DENSE_RANK() OVER(ORDER BY TBL.A, TBL.B, TBL.C ASC) AS C_NUM
               ,TBL.D
               ,TBL.E
               ,TBL.F
        FROM TABLE TBL
    )X
)-- END OF WITH 

SELECT CASE WHEN PARTNER_NUM <> NVL(PRE_A_NUM, -1) THEN A ELSE NULL END AS A
      ,CASE WHEN PLANT_NUM   <> NVL(PRE_B_NUM, -1) THEN B ELSE NULL END AS B
      ,CASE WHEN PURDOC_NUM  <> NVL(PRE_C_NUM, -1) THEN C ELSE NULL END AS C
      ,TBL.D
      ,TBL.E
      ,TBL.F
FROM TBL